settings:
  variables:
    entity_tablet: switch.lenovotab_screensaver
    entity_browser_mod: media_player.tablet

    translate_unknown: Indisponible
    translate_idle: Inactif
    translate_home: Présent
    translate_not_home: Absent
    translate_available: disponible
    translate_no_updates: Pas de mise à jour
    translate_update_available: mise à jour disponible
    translate_updates_available: mises à jour disponibles

    translate_on: "Actif"
    translate_off: "Inactif"
    translate_cool: Froid
    translate_fan_only: Ventilateur uniquement
    translate_playing: Lecture
    translate_paused: Pause
    translate_standby: standby
