homeassistant:
  name: Maison
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Paris
  language: fr
  country: FR
  currency: EUR
  packages: !include_dir_named packages
  customize_domain:
    automation:
      initial_state: true
  allowlist_external_dirs:
    - /config
  external_url: !secret external_url
  internal_url: !secret internal_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy
    
default_config:

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

template: !include sidebar.yaml

lovelace:
  mode: yaml
  resources:
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js,                               type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                   type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                  type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,  type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },
      { url: /hacsfiles/tabbed-card/tabbed-card.js,                                 type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                  type: module },

      { url: '/local/marked.min.js?v=4.3.0',                                        type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.8.0',                                  type: module },
      { url: '/local/browser_mod_icon.js?v=0.5',                                    type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css }
    ]

# recorder:
#   db_url: !secret recorder_db_url
#   exclude:
#     entity_globs:
#       - sensor.browser_*

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influx_homeassistant_user
  password: !secret influx_homeassistant_password
  max_retries: 3
  default_measurement: state
  include:
    entity_globs:
      - sensor.*_temperature
      - sensor.temperature_*
      - sensor.smart_plug_*

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    custom_components.monitor_docker.helpers: error
    homeassistant.setup: error
    homeassistant.components.command_line.sensor: error
    homeassistant.components.rest.sensor: error
    homeassistant.helpers.service: error
    homeassistant.components.media_player: error
    homeassistant.helpers.entity: error
    homeassistant.helpers.event: fatal
    homeassistant.components.ipp: fatal
    homeassistant.helpers.template: error
    custom_components.xiaomi_miio_fan.fan: critical

sensor:
  - platform: time_date
    display_options:
      - time
      - date

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

meteo_france:
  - city: !secret cp
