homeassistant:
  name: Maison
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]
  external_url: "https://hass.kaoru.fr"
  internal_url: "http://192.168.1.200:8123"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml


lovelace:
  mode: yaml
  resources:
    [ {url: /hacsfiles/bar-card/bar-card.js,                                  type: module},
      {url: /hacsfiles/button-card/button-card.js,                            type: module},
      {url: /hacsfiles/kiosk-mode/kiosk-mode.js,                              type: module},
      {url: /hacsfiles/light-entity-card/light-entity-card.js,                type: module},
      {url: /hacsfiles/light-popup-card/light-popup-card.js,                  type: module},
      {url: /hacsfiles/lovelace-card-mod/card-mod.js,                         type: module},
      {url: /hacsfiles/lovelace-hui-element/hui-element.js,                   type: module},
      {url: /hacsfiles/lovelace-layout-card/layout-card.js,                   type: module},
      {url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,       type: module},
      {url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,             type: module},
      {url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,         type: module},
      {url: /hacsfiles/swipe-card/swipe-card.js,                              type: module},
      {url: /hacsfiles/spotify-card/spotify-card.js,                          type: module},
      {url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,         type: module},
      {url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js,       type: module},

      {url: '/local/calendar-card.js?v=31091',                                type: module},
      {url: '/local/stack-in-card.js?v=101',                                  type: module},
      {url: '/local/custom_icons.js?v=25052001',                              type: module},
      {url: /local/font.css,                                                     type: css} ]

logger:
  default: warning
  logs:
    homeassistant.components.homekit.type_media_players: error
    homeassistant.components.command_line.sensor: error
    homeassistant.components.rest.sensor: error
    bravia_tv.braviarc: error
    homeassistant.components.websocket_api: fatal
    homeassistant.helpers.service: error
    homeassistant.components.media_player: error
    homeassistant.helpers.entity: error
    homeassistant.helpers.event: fatal
    homeassistant.components.ipp: fatal

recorder:
  purge_keep_days: 2
  include:
    entities:
      ['person.kaoru', 'person.papa', 'sensor.network_throughput_in_eth0', 'sensor.network_throughput_out_eth0', 'sensor.myenedis',
      'sensor.average_temperature']
    entity_globs:
      ['sensor.temperature_*', 'sensor.*_temperature', 'sensor.humidity_*' ]

browser_mod:
  devices:
    b6179c71-98d8b4f9:
      name: kaoru_chrome
    9b63bbf0_40273ef4:
      name: tablet
    7892df5b-5535b94b:
      name: app_chrome

hacs:
  token: !secret hacs_token

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

tts:
  - platform: google_translate
    language: 'fr'

meteo_france:
  - city: '59650'

samsungtv:
  - host: !secret samsungtv_host
    name: samsung_tv_remote
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret samsungtv_mac

# media_player:
#   - platform: samsungtv_custom
#     host: !secret samsungtv_host
#     mac: !secret samsungtv_mac
#     port: 8001
#     sourcelist: '{"Bbox": "KEY_HDMI1", "Console": "KEY_HDMI2", "IPTV": "KEY_HDMI3"}'

# media_player:
#   - platform: samsungtv_tizen
#     host: !secret samsungtv_host
#     mac: !secret samsungtv_mac

shell_command:

  ha_dockermon_restart_container: !secret ha_dockermon_restart_container
  clear_logs: truncate -s 0 /config/home-assistant.log

  ha_update: !secret ha_update
  google_home_get_token: !secret google_home_get_token
  enedis_update_data: !secret enedis_update_data

light:
  - platform: group
    name: CHAMBRE
    entities: ['light.yeelight_stripe', 'light.plafond_1', 'light.plafond_2', 'light.lampe_japonaise']

  - platform: group
    name: BUREAU
    entities: ['light.yeelight_stripe', 'light.lampe_japonaise']

  - platform: group
    name: PLAFOND
    entities: ['light.plafond_1', 'light.plafond_2']

  - platform: group
    name: SALON
    entities: ['light.salon_1', 'light.salon_2']

  - platform: group
    name: MAISON
    entities: ['light.yeelight_stripe', 'light.plafond_1', 'light.plafond_2', 'light.lampe_japonaise', 'light.salon_1', 'light.salon_2']
