class BboxConstant:

    HTTP_METHOD_GET = "get"
    HTTP_METHOD_PUT = "put"
    HTTP_METHOD_POST = "post"
    DEFAULT_LOCAL_IP = "192.168.1.254"
    DEFAULT_REMOTE_PORT = "443"
    API_DEVICE = "device"
    API_HOSTS = "hosts"
    API_WAN = "wan"
    API_WIFI = "wireless"
    AUTHENTICATION_TYPE_LOCAL = 0
    AUTHENTICATION_TYPE_REMOTE = 1
    AUTHENTICATION_LEVEL_PUBLIC = 2
    AUTHENTICATION_LEVEL_PRIVATE = 1
    AUTHENTICATION_LEVEL_NONE = 0
    COOKIE_BBOX_ID = "BBOX_ID"

    def __init__(self):
        pass
