
homeassistant:
  customize:

    ####################################################
    #                                                  #
    #                    CUSTOMIZE                     #
    #                                                  #
    ####################################################


    binary_sensor.rpi_internet_access:
      icon: mdi:web
      friendly_name: Internet

    binary_sensor.plex_availability:
      icon: mdi:plex

    sensor.synology_maximum_disk_temp_volume_1:
      friendly_name: Disktemperatur

    sensor.hall_temperature:
      friendly_name: Température

    sensor.processor_temperature:
      icon: mdi:thermometer  

    sensor.processor_use:
      icon: mdi:chip

    sensor.aktuellt_spotpris:
      icon: mdi:home-currency-usd

    sensor.fullykiosk:
      icon: mdi:tablet-dashboard

    sensor.docker_cpu:
      friendly_name: Processeur
      icon: mdi:chip

    sensor.docker_uptime:
      friendly_name: Dernier rédémarrage
      icon: mdi:update

    sensor.last_boot:
      icon: mdi:calendar-clock

    ### William computer ###
    sensor.computer_rig_kaoru_uptime:
      icon: mdi:calendar-clock

    sensor.computer_rig_kaoru_disk_c_usage:
      friendly_name: System NVME
      icon: custom:imac-ssd

    sensor.computer_rig_kaoru_disk_d_usage:
      friendly_name: HDD
      icon: mdi:harddisk
    sensor.computer_rig_kaoru_disk_g_usage:
      friendly_name: Games NVME
      icon: custom:imac-ssd

    sensor.computer_rig_kaoru_cpu_usage:
      friendly_name: Processeur
      icon: mdi:chip

    sensor.computer_rig_kaoru_ram_usage:
      friendly_name: Mémoire
      icon: mdi:memory

    ### Papa computer ###
    sensor.computer_papa_uptime:
      icon: mdi:calendar-clock

    sensor.computer_papa_disk_c_usage:
      friendly_name: System SSD
      icon: custom:imac-ssd

    sensor.computer_papa_disk_d_usage:
      friendly_name: HDD
      icon: mdi:harddisk

    sensor.computer_papa_cpu_usage:
      friendly_name: Processeur
      icon: mdi:chip

    sensor.computer_papa_ram_usage:
      friendly_name: Mémoire
      icon: mdi:memory


    sensor.monitors_volume:
      icon: mdi:volume-high

    sensor.home_assistant_v2_db:
      friendly_name: Base de données 
      icon: mdi:database

    sensor.home_assistant_log:
      friendly_name: Fichier journal
      icon: mdi:file-document


    #media_player

    # media_player.sony_bravia:
    #   friendly_name: Tv
    #   device_class: tv
    #   source_list: ['HDMI 1', 'HDMI 2/MHL', 'HDMI 3', 'HDMI 4']

    media_player.samsung_tv_remote:
      friendly_name: "TV"
      device_class: tv
      source_list: ['TV', 'HDMI1', 'HDMI2', 'HDMI3']


    #person

    # person.mattias:
    #   entity_picture: '/local/mattias.png'
    # person.sanja:
    #   entity_picture: '/local/sanja.png'

    person.kaoru:
      entity_picture: '/local/kaoru.jpg'

    person.papa:
      entity_picture: '/local/papa.jpg'

    #light

    # light.fonsterlampa:
    #   friendly_name: Skrivbordslampa
    #   icon: mdi:lamp

    # light.badrum:
    #   icon: mdi:toilet

    # light.storlampa:
    #   friendly_name: Storlampa
    #   icon: mdi:silverware-fork-knife

    # light.kladkammare_2:
    #   friendly_name: Garderob
    #   icon: mdi:door

    # light.hall:
    #   icon: mdi:track-light

    # light.taklampor:
    #   icon: mdi:track-light

    # light.mattias:
    #   icon: mdi:floor-lamp

    # light.sanja:
    #   icon: mdi:floor-lamp

    # light.spot_1:
    #   friendly_name: Taklampa 1

    # light.spot_2:
    #   friendly_name: Taklampa 2


    #switch

    # switch.wemo_monitors:
    #   friendly_name: Monitorer
    #   icon: custom:studio-monitor

    switch.watchtower:
      icon: custom:docker-watchtower

    switch.fullykiosk_screen:
      icon: mdi:tablet


    #fan

    # fan.studio_wemo:
    #   icon: custom:pedestal-fan

    # fan.sovrum_anslut:
    #   icon: custom:pedestal-fan


    #automation

    # automation.tv_on_lights:
    #   friendly_name: Tänd Tv-lampa

    automation.macos_notification_motion_hall:
      friendly_name: Mottag notiser
      icon: mdi:bell

    # automation.turn_off_monitors:
    #   friendly_name: Stäng av när dator stängs av
    #   icon: mdi:power

    # automation.eq_calibration:
    #   friendly_name: Automatisk kalibrationsprofil
    #   icon: custom:eq-calibrate

    # automation.sovrum_anslut_turn_on_temp:
    #   friendly_name: Slå på om 24 °C överskrids
    #   icon: mdi:chart-bell-curve-cumulative


    #device_tracker

    # device_tracker.iphone:
    #   entity_picture: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 50 50'%3E%3Cpath d='M0 0h50v50H0z' fill='%23f7f7f7'/%3E%3Cg fill='%23070707'%3E%3Cpath d='M30.9 9.4H19.1a2.65 2.65 0 0 0-2.6 2.6v26a2.65 2.65 0 0 0 2.6 2.6H31a2.65 2.65 0 0 0 2.6-2.6V12c-.1-1.4-1.2-2.6-2.7-2.6zM32 38a1.11 1.11 0 0 1-1.1 1.1H19.1A1.11 1.11 0 0 1 18 38V12a1.11 1.11 0 0 1 1.1-1.1H21c.2 0 .4.2.4.4a1.11 1.11 0 0 0 1.1 1.1h5.2a1.11 1.11 0 0 0 1.1-1.1c0-.2.2-.4.4-.4h1.9a1.11 1.11 0 0 1 1.1 1.1v26z'/%3E%3Cpath d='M30.9 40.8H19.1c-1.6 0-2.8-1.3-2.8-2.8V12c0-1.6 1.3-2.8 2.8-2.8H31c1.6 0 2.8 1.3 2.8 2.8v26c0 1.5-1.3 2.8-2.9 2.8zM19.1 9.7c-1.3 0-2.3 1.1-2.3 2.3v26c0 1.3 1.1 2.3 2.3 2.3H31c1.3 0 2.3-1.1 2.3-2.3V12c0-1.3-1.1-2.3-2.3-2.3H19.1zm11.8 29.6H19.1c-.8 0-1.4-.6-1.4-1.4V12c0-.8.6-1.4 1.4-1.4H21a.65.65 0 0 1 .6.6c0 .5.4.9.9.9h5.2c.5 0 .9-.4.9-.9a.65.65 0 0 1 .6-.6h1.9c.8 0 1.4.6 1.4 1.4v26c-.2.7-.8 1.3-1.6 1.3zM19.1 11.2c-.5 0-.9.4-.9.9V38c0 .5.4.9.9.9H31c.5 0 .9-.4.9-.9V12c0-.5-.4-.9-.9-.9h-1.9c-.1 0-.1.1-.1.1 0 .8-.6 1.4-1.4 1.4h-5.2c-.8 0-1.4-.6-1.4-1.4 0-.1-.1-.1-.1-.1h-1.8z'/%3E%3C/g%3E%3C/svg%3E"
