switch:
  - platform: wake_on_lan
    name: wol_rig_kaoru
    mac: !secret wake_on_lan_kaoru_mac
    host: !secret wake_on_lan_kaoru_host
    broadcast_address: 192.168.1.255

  - platform: template
    switches:
      computer_rig_kaoru:
        friendly_name: Kaoru
        icon_template: cil:imac-alternative
        value_template: "{{ is_state('switch.wol_rig_kaoru', 'on') }}"
        turn_on:
          - action: switch.turn_on
            target:
              entity_id: switch.wol_rig_kaoru
          - action: script.turn_on
            target:
              entity_id: script.computer_rig_kaoru_load
        turn_off:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.computer_rig_kaoru_lock
                    state: "on"
                sequence:
                  - service: browser_mod.toast
                    data:
                      duration: 8000
                      message: L'ordinateur est verrouillé...
            default:
              - action: switch.turn_on
                target:
                  entity_id: switch.rig_kaoru_shutdown
              - action: script.turn_on
                target:
                  entity_id: script.computer_rig_kaoru_load

input_boolean:
  computer_rig_kaoru_lock:
    name: Verrouillage
    icon: mdi:lock
  computer_rig_kaoru_load:
    name: Load
    icon: mdi:reload

template:
  sensor:
    - name: rig_kaoru_storage_c_used_space_percentage
      unit_of_measurement: "%"
      state: "{{ state_attr('sensor.rig_kaoru_storage_c', 'UsedSpacePercentage') }}"
    - name: rig_kaoru_storage_d_used_space_percentage
      unit_of_measurement: "%"
      state: "{{ state_attr('sensor.rig_kaoru_storage_d', 'UsedSpacePercentage') }}"
    - name: rig_kaoru_storage_g_used_space_percentage
      unit_of_measurement: "%"
      state: "{{ state_attr('sensor.rig_kaoru_storage_g', 'UsedSpacePercentage') }}"
    - name: rig_kaoru_uptime
      state: >
        {% set startup_time_state = states('sensor.rig_kaoru_lastboot') %}
        {% if startup_time_state not in ['unknown', 'unavailable'] %}
          {% set now = as_timestamp(now()) %}
          {% set startup_time = as_timestamp(strptime(startup_time_state, "%Y-%m-%dT%H:%M:%S%z")) %}
          {% set uptime_seconds = now - startup_time %}
          {% set uptime_hours = (uptime_seconds / 3600) | int %}
          {% set uptime_minutes = ((uptime_seconds % 3600) / 60) | int %}
          {{ "{:02d}:{:02d}".format(uptime_hours, uptime_minutes) }}
        {% else %}
          Pas encore disponible
        {% endif %}

homeassistant:
  customize:
    sensor.rig_kaoru_uptime:
      friendly_name: Uptime
      icon: mdi:calendar-clock

    sensor.rig_kaoru_storage_c_used_space_percentage:
      friendly_name: System NVME
      icon: cil:imac-ssd

    sensor.rig_kaoru_storage_d_used_space_percentage:
      friendly_name: HDD
      icon: mdi:harddisk

    sensor.rig_kaoru_storage_g_used_space_percentage:
      friendly_name: Games NVME
      icon: cil:imac-ssd

    sensor.rig_kaoru_cpuload:
      friendly_name: Processeur
      icon: mdi:chip

    sensor.rig_kaoru_memoryusage:
      friendly_name: Mémoire
      icon: mdi:memory

script:
  computer_rig_kaoru_load:
    alias: computer_rig_kaoru_load
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.computer_rig_kaoru_load
      - wait_for_trigger:
          - platform: state
            entity_id: switch.computer_rig_kaoru
        timeout: "00:10:00"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.computer_rig_kaoru_load
    mode: single

automation:
  - alias: rig_kaoru_screenshot
    mode: single
    triggers:
      - trigger: time_pattern
        minutes: /5
    actions:
      - action: button.press
        target:
          entity_id: button.rig_kaoru_screenshot
        data: {}
    conditions:
      - condition: state
        entity_id: switch.computer_rig_kaoru
        state: "on"

        #camera:
#  - platform: local_file
#    file_path: /media/RIG-KAORU-screenshot.png
#    name: "rig_kaoru"
