sensor:
  - platform: average
    precision: 1
    name: average_consumption
    entities:
      - sensor.lixee_zlinky_tic_apparent_power
    duration:
      days: 1

utility_meter:
  monthly_energy:
    source: sensor.lixee_zlinky_tic_summation_delivered
    cycle: monthly
  daily_energy:
    source: sensor.lixee_zlinky_tic_summation_delivered
    cycle: daily
