homeassistant:
  customize:
    sensor.os_version:
      friendly_name: OS

sensor:
  - platform: rest
    resource: http://localhost:8080/api/speedtest/latest
    name: Speedtest download
    value_template: "{{ value_json['data']['download'] }}"
    unit_of_measurement: Mbps
  - platform: rest
    resource: http://localhost:8080/api/speedtest/latest
    name: Speedtest upload
    value_template: "{{ value_json['data']['upload'] }}"
    unit_of_measurement: Mbps
  - platform: rest
    resource: http://localhost:8080/api/speedtest/latest
    name: Speedtest ping
    value_template: "{{ value_json['data']['ping'] }}"
    unit_of_measurement: ms

  #not supported anymore
  # - platform: systemmonitor
  #   resources:
  #     - type: disk_use_percent
  #       arg: /
  #     - type: processor_use
  #     - type: memory_use_percent
  #     - type: last_boot
  #     - type: throughput_network_in
  #       arg: enp6s18
  #     - type: throughput_network_out
  #       arg: enp6s18

  # https://github.com/NemesisRE/sensor.plex_recently_added
  # - platform: plex_recently_added
  #   token: !secret plex_token
  #   host: !secret plex_host
  #   port: !secret plex_port
  #   max: 1
  #   img_dir: '/'
  #   image_resolution: 800

template:
  - sensor:
      - unique_id: domain_counter
        state: >
          {{ states | count }}
        attributes:
          automation: >
            {{ states.automation | count }}
          binary_sensor: >
            {{ states.binary_sensor | count }}
          device_tracker: >
            {{ states.device_tracker | count }}
          light: >
            {{ states.light | count }}
          media_player: >
            {{ states.media_player | count }}
          sensor: >
            {{ states.sensor | count }}
          switch: >
            {{ states.switch | count }}
          other: >
            {% set exclude = this.attributes | list %}
            {{ states | rejectattr('domain', 'in', exclude) | list | count }}

shell_command:
  purge_log: truncate -s 0 /config/home-assistant.log

automation:
  - alias: purge_log_filesize
    id: "3331821824310"
    trigger:
      platform: numeric_state
      entity_id: sensor.home_assistant_log_size
      above: 50
    action:
      service: shell_command.purge_log

  - alias: auto_snapshot
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: hassio.backup_full
        data:
          name: >-
            auto_backup_{{ states("sensor.date") | replace("-", "")}}_{{
            states("sensor.time") | replace(":", "") }}
