homeassistant:
  customize:
    switch.lenovotab_screensaver:
      friendly_name: Économiseur d'écran
      icon: mdi:power-sleep
    number.lenovotab_screen_brightness:
      friendly_name: Ecran
      icon: mdi:tablet
    switch.lenovotab_screen:
      friendly_name: Ecran
      icon: mdi:tablet
    binary_sensor.lenovotab_plugged_in:
      friendly_name: Branché
      icon: mdi:power-plug
    sensor.lenovotab_last_app_start:
      friendly_name: Dernier redémarrage
      icon: mdi:update
    sensor.lenovotab_battery:
      friendly_name: Batterie

template:
  - sensor:
      - unique_id: fullykiosk_storage
        state: >
          {% set FreeSpace = states('sensor.lenovotab_internal_storage_free_space') | float(default=0) %}
          {% set TotalSpace = states('sensor.lenovotab_internal_storage_total_space') | float(default=0) %}
          {% if not (FreeSpace == 0.0 or TotalSpace == 0.0) %}
            {{ 100 - (FreeSpace / TotalSpace * 100) | int(default=0) }}
          {% endif %}
        attributes:
          friendly_name: Stockage
          icon: mdi:sd
          unit_of_measurement: "%"

      - unique_id: fullykiosk_memory
        state: >
          {% set FreeMemory = states('sensor.lenovotab_free_memory') | float(default=0) %}
          {% set TotalMemory = states('sensor.lenovotab_total_memory') | float(default=0) %}
          {% if not (FreeMemory == 0.0 or TotalMemory == 0.0) %}
            {{ 100 - (FreeMemory / TotalMemory * 100) | int(default=0) }}
          {% endif %}
        attributes:
          friendly_name: RAM
          icon: mdi:memory
          unit_of_measurement: "%"

automation:
  - alias: homeassistant_start
    id: "7426848686945"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: button.press
        target:
          entity_id: button.lenovotab_load_start_url

  - alias: notify_tablet_unplugged
    id: "3972668118831"
    trigger:
      platform: numeric_state
      entity_id: sensor.lenovotab_batterie
      below: 30
    action:
      service: notify.all_devices
      data:
        title: Chargement de la tablette...
        message: >
          Batterie {{ states(trigger.entity_id) }}%

  - alias: back_home_tablet
    id: "345538118831"
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - sensor.tablet_browser_path
        for:
          hours: 0
          minutes: 5
          seconds: 0
    conditions:
      - condition: and
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.tablet_browser_path
                state: /lovelace/home
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.tablet_browser_path
                state: /lovelace/default_view
    actions:
      - action: browser_mod.navigate
        metadata: {}
        data:
          browser_id:
            - 6c1e502969ee705227e70afe410e1349
          path: /lovelace/default_view?kiosk

  # - alias: fullykiosk_screensaver
  #   id: '9452750674803'
  #   mode: restart
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.hall_motion_motion
  #       from: 'off'
  #       to: 'on'
  #     - platform: state
  #       entity_id: light.hall
  #       from: 'on'
  #       to: 'off'
  #   action:
  #     if: >
  #       {{ 'hall_motion_motion' in trigger.entity_id }}
  #     then:
  #       - service: switch.turn_off
  #         target:
  #           entity_id: switch.lenovotab_screensaver
  #       - service: number.set_value
  #         target:
  #           entity_id: number.lenovotab_screen_brightness
  #         data:
  #           value: >
  #             {% set day_percent = 90 %}
  #             {% set night_percent = 65 %}
  #             {% set day_convert = ((day_percent * 255) / 100) | int %}
  #             {% set night_convert = ((night_percent * 255) / 100) | int %}
  #             {{ iif(is_state('sun.sun', 'above_horizon'), day_convert, night_convert) }}
  #     else:
  #       - service: switch.turn_on
  #         target:
  #           entity_id: switch.lenovotab_screensaver
  #       - delay:
  #           minutes: 15
  #       - service: browser_mod.close_popup
  #         data:
  #           browser_id: tablet
