light:
  - platform: group
    name: CHAMBRE
    entities:
      [
        "light.yeelight_stripe",
        "light.plafond_1",
        "light.plafond_2",
        "light.lampe_japonaise",
      ]

  - platform: group
    name: BUREAU
    entities: ["light.yeelight_stripe", "light.lampe_japonaise"]

  - platform: group
    name: PLAFOND
    entities: ["light.plafond_1", "light.plafond_2"]

  - platform: group
    name: SALON
    entities: ["light.salon_1", "light.salon_2"]

  - platform: group
    name: MAISON
    entities:
      [
        "light.yeelight_stripe",
        "light.plafond_1",
        "light.plafond_2",
        "light.lampe_japonaise",
        "light.salon_1",
        "light.salon_2",
        "light.switch_wall_cuisine"
      ]

template:
  - sensor:
      - name: "Total Lights Count Template"
        state: "{{ states.light | rejectattr('attributes.entity_id', 'defined') | selectattr('state', 'eq', 'on') | rejectattr('attributes.type', 'equalto', 'browser_mod') | list | count }}"

automation:
  - alias: toggle_bureau
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_short_press
        subtype: remote_button_short_press
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_short_press
        subtype: remote_button_short_press
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_short_press
        subtype: remote_button_short_press
        trigger: device
    condition: []
    action:
      - action: light.toggle
        target:
          entity_id: light.bureau
    mode: single

  - alias: toggle_plafond
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_double_press
        subtype: remote_button_double_press
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_double_press
        subtype: remote_button_double_press
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_double_press
        subtype: remote_button_double_press
        trigger: device
    condition: []
    action:
      - action: light.toggle
        target:
          entity_id: light.plafond

  - alias: allumer_chambre
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
    condition:
      - condition: state
        state: "off"
        entity_id: light.chambre
    action:
      - action: light.turn_on
        target:
          entity_id: light.chambre
    mode: single

  - alias: eteindre_chambre
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
    condition:
      - condition: state
        state: "on"
        entity_id: light.chambre
    action:
      - action: light.turn_off
        target:
          entity_id: light.chambre
