light:
  - platform: group
    name: CHAMBRE
    entities:
      [
        "light.yeelight_stripe",
        "light.plafond_1",
        "light.plafond_2",
        "light.lampe_japonaise",
      ]

  - platform: group
    name: BUREAU
    entities: ["light.yeelight_stripe", "light.lampe_japonaise"]

  - platform: group
    name: PLAFOND
    entities: ["light.plafond_1", "light.plafond_2"]

  - platform: group
    name: SALON
    entities: ["light.salon_1", "light.salon_2"]

  - platform: group
    name: MAISON
    entities:
      [
        "light.yeelight_stripe",
        "light.plafond_1",
        "light.plafond_2",
        "light.lampe_japonaise",
        "light.salon_1",
        "light.salon_2",
        "light.switch_wall_cuisine",
        "light.switch_wall_chambre_papa",
        "light.switch_wall_toilette",
        "light.switch_wall_salle_de_bain"
      ]

template:
  - sensor:
      - name: "total_lights_on"
        state: "{{ states.light | rejectattr('attributes.entity_id', 'defined') | selectattr('state', 'eq', 'on') | rejectattr('attributes.type', 'equalto', 'browser_mod') | list | count }}"
        attributes:
          friendly_name: Total Lights On

automation:
  - alias: toggle_bureau
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_short_press
        subtype: remote_button_short_press
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_short_press
        subtype: remote_button_short_press
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_short_press
        subtype: remote_button_short_press
        trigger: device
    condition: []
    action:
      - action: light.toggle
        target:
          entity_id: light.bureau
    mode: single

  - alias: toggle_plafond
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_double_press
        subtype: remote_button_double_press
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_double_press
        subtype: remote_button_double_press
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_double_press
        subtype: remote_button_double_press
        trigger: device
    condition: []
    action:
      - action: light.toggle
        target:
          entity_id: light.plafond

  - alias: turn_on_chambre
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
    condition:
      - condition: state
        state: "off"
        entity_id: light.chambre
    action:
      - action: light.turn_on
        target:
          entity_id: light.chambre
    mode: single

  - alias: turn_off_chambre
    trigger:
      - device_id: 3f7bf0b1d53cb13c4212ef835580c4ca
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: d9bf413036f7a7482d2681625d07bf0d
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
      - device_id: 880038593f81e164554c496e37d93153
        domain: zha
        type: remote_button_long_press
        subtype: button
        trigger: device
    condition:
      - condition: state
        state: "on"
        entity_id: light.chambre
    action:
      - action: light.turn_off
        target:
          entity_id: light.chambre

  - alias: auto_turn_off_cuisine
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - light.switch_wall_cuisine
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 20
          seconds: 0
    conditions:
      - condition: time
        after: "22:00:00"
        before: "07:00:00"
      - condition: state
        entity_id: light.switch_wall_cuisine
        state: "on"
    actions:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_cuisine
    mode: single

  - alias: auto_turn_off_chambre_papa
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - light.switch_wall_chambre_papa
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 20
          seconds: 0
    conditions:
      - condition: time
        after: "22:00:00"
        before: "07:00:00"
      - condition: state
        entity_id: light.switch_wall_chambre_papa
        state: "on"
    actions:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_chambre_papa
    mode: single

  - alias: toggle_cuisine
    description: ""
    triggers:
      - device_id: 631a266451fd7ad699e580f912b7fbf9
        domain: zha
        type: remote_button_short_press
        subtype: left
        trigger: device
    conditions: []
    actions:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_cuisine
    mode: single

  - alias: auto_turn_on_salle_de_bain
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.pir_salle_de_bain
        to: "on"
    conditions:
      - condition: state
        entity_id: light.switch_wall_salle_de_bain
        state: "off"
    actions:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_salle_de_bain
    mode: single

  - alias: auto_turn_off_salle_de_bain
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.pir_salle_de_bain
        to: "off"
    conditions:
      - condition: state
        entity_id: light.switch_wall_salle_de_bain
        state: "on"
    actions:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_salle_de_bain
    mode: single

  - alias: auto_turn_on_toilette
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.pir_wc
        to: "on"
    conditions:
      - condition: state
        entity_id: light.switch_wall_toilette
        state: "off"
    actions:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_toilette
    mode: single

  - alias: auto_turn_off_toilette
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.pir_wc
        to: "off"
    conditions:
      - condition: state
        entity_id: light.switch_wall_toilette
        state: "on"
    actions:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.switch_wall_toilette
    mode: single