automation:

  - alias: dismiss_lovelace_updated
    id: '1309195316329'
    mode: restart
    trigger:
      platform: event
      event_type: lovelace_updated
    action:
      repeat:
        count: 5
        sequence:
          - delay: 0.5
          - service: browser_mod.notification
            data:
              duration: 1
              message: ' '

  - alias: notify_hass_update
    id: '7958228563778'
    trigger:
      platform: state
      entity_id:
        - sensor.hass_release_notes
        - sensor.hass_release_notes_beta
    condition: >
      {{ state_attr('sensor.template_updates', 'home_assistant') == 1 }}
    action:
      - service: homeassistant.update_entity
        target:
          entity_id:
            - sensor.hass_release_notes
            - sensor.hass_release_notes_beta
      - delay:
          minutes: 15
      - service: notify.mobile_app_oneplus12
        data:
          title: >
            {% set installed = states('sensor.current_version') %}
            {{ states('sensor.hass_release_notes') if version(installed).beta
            else states('sensor.hass_release_notes') }} disponible {{ '\U0001F389' }}
          message: Maintenir la touche enfoncée pour mettre à jour
          data:
            url: https://www.home-assistant.io/latest-release-notes/
            actions:
              - action: START_HA_UPDATE
                title: Mise à jour

  - alias: notify_hass_update_action
    id: '0694774018396'
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: START_HA_UPDATE
    actions:
      - action: update.install
        data:
          backup: true
        target:
          entity_id: update.home_assistant_core_update